### PR TITLE
remove pyspark dependency

### PR DESCRIPTION
**Pull request by teonbrooks**
...to avoid conflict with `databricks-connect`

### CODE REVIEW

**Comment by teonbrooks** [comment]
in both instances of running databricks: web portal or databricks-connect, `pyspark` would be included in the environment. in the [setup](https://docs.databricks.com/user-guide/dev-tools/db-connect.html) for db-connect, it requires removing any already installed versions of `pyspark`. having it as a requirement for dscontrib will likely lead to incompatibility.

**Comment by felixlawrence** [comment]
Is this interfering with your workflow (and we should fix this ASAP) or is it an anticipated problem (so can think before acting)?

So _in theory_ we need to specify dependencies on one of the following:
1) The hosted databricks stack (i.e. what's pre-installed in our databricks notebooks), or
2)  `databricks-connect`
3) `pyspark` et al

I think we can get away without support for (3) in this repo - the main reason to have non-databricks pyspark would be for testing, and at this time we're not planning to do testing in this repo (reliable code lives elsewhere!)

Is there a straightforward and elegant way to express the (1) and (2) dependencies in `setup.py`?

If not, then pragmatically, I think this PR won't cause problems for this repo's users so IMO we can probably live with this as a long term behavior.

**Comment by teonbrooks** [comment]
> Is this interfering with your workflow (and we should fix this ASAP) or is it an anticipated problem (so can think before acting)?

i made a local fix since I have a fork of project instead of using pip. I noticed when I ran setup.py that it began to download it. i didn't want to mess up my local environment and have suspicion that databricks isn't offering guarantees with the latest version of pyspark and db-connect.


> Is there a straightforward and elegant way to express the (1) and (2) dependencies in `setup.py`?

followed it up with an inspection for `databricks-connect`. that should work

**Comment by teonbrooks** [comment]
do we need `py4j` and `pyarrow`. i saw that we weren't calling them and I think it was just borrowed from mozanalysis but I can add them about if we think they're useful to have

**Comment by felixlawrence** [comment]
Let's exclude `py4j` and `pyarrow` until someone asks to put them back in.

I'm nervouse about the `shutil` check - surely it's liable to backfiring (e.g. if there are `$PATH` issues, changes to the installation order, etc). So let's go back to 19022c8 and merge it?

**Pull request merged**
